### ISSUE TITLE
Thoughts on creating and updating

### ISSUE THREAD

**Issue by janpeterka** [Intrepidd/hyperactiveform#1]
Hi, this gem looks nice, but from documentation it's not clear (to me) how to navigate pretty standard case: I have form `ItemForm`, and I want to use it for both creation and updating of `Items`.

I guess the simple way is to have
```ruby
def perform
	if @item.persisted?
		# do creation logic
    else
		# do updation logic
```
, or is it expected to have `CreateItemForm` and `UpdateItemForm`?

I can imagine both, for now it might just be helpful to describe this in readme.

Thanks, I'm curious about future development, and possibly will try this gem in my new project!

**Comment by Intrepidd** [comment]
it kinda depends on what your form look like. If the create and edit form look the same, you can have an `ItemForm` that takes the record as param, and juste `.update` it regardless of its persisted state. 

If your create and edit form are completely different and touch different attributes, you can have an `Items::CreateForm` and `Items::EditForm` that each handles the different use case.

Is it more clear ? 

I might add an `examples` folder to showcase the expected usage

**Comment by janpeterka** [comment]
Great, thanks a lot!
